### ISSUE TITLE
Play button doesn't work with video.js 6.2.0 and webpack

### ISSUE THREAD

**Issue by alsar** [collab-project/videojs-record#149]
## Description
Playing the recorded video doesn't work with video.js ~~6.0.0~~ ~6.2.0
When you record a video and then press the play button noting happens.

## Steps to reproduce
Install video.js ~6.2.0

### Expected
Should play the video.

### Error output
```
Uncaught TypeError: videojs.getComponent is not a function
```

#### videojs
what version of videojs does this occur with?
video.js 6.2.0
videojs-record 1.6.1
#### browsers
what browser are affected?
Tested in Firefox and Chrome
#### OSes
what platforms (operating systems and devices) are affected?
Linux

**Comment by thijstriemstra** [comment]
Have to test this.

**Comment by thijstriemstra** [comment]
It works in Firefox (53) now but not in Chrome (60), closed this to soon.

**Comment by thijstriemstra** [comment]
@alsar can you confirm it's working now with the latest master?

**Comment by alsar** [comment]
@thijstriemstra With 6.2.0 i get an `Uncaught TypeError: videojs.getComponent is not a function`error.

**Comment by alsar** [comment]
With 6.1.0 it works now in both Firefox and Chrome.

**Comment by thijstriemstra** [comment]
@alsar really, it works with 6.1.0 but not with 6.2.0?

**Comment by alsar** [comment]
Yes, is looks that way.

**Comment by thijstriemstra** [comment]
what os/version of firefox/chrome? I can't reproduce that..

**Comment by alsar** [comment]
Firefox 54 and Chromium 58. Maybe it's an Webpack problem. 
I'll investigate in the next days and get back to you.

**Comment by perminder-klair** [comment]
Getting same issue with

```
    "video.js": "^6.1.0",
    "videojs-record": "^1.6.2"
```

`TypeError: videojs.getComponent is not a function`

**Comment by thijstriemstra** [comment]
What line does this error occur on? Can someone post a screenshot or stacktrace? (with unminified versions)

**Comment by thijstriemstra** [comment]
This fix in a different plugin could be related: https://github.com/videojs/videojs-youtube/commit/ad7275caf4b9d102354fbceda86ab9f20e216ee8#diff-41489607c076711cf7440b328fb7a065R37.

**Comment by thijstriemstra** [comment]
Also tested on OSX with Chrome 60.0.3112.40, still cannot reproduce.

**Comment by alsar** [comment]
@thijstriemstra  I could get down to the root of the problem.
The problem is the combination of ES6 exports `export default videojs` and requirejs imports `require('video.js)`

video.js switched from `module.exports = videojs` in 6.1.0 to `export default videojs` in 6.2.0
And while videojs-record still uses require('video.js) and if you use ES6 stops working. 

https://github.com/videojs/video.js/blob/v6.1.0/src/js/video.js#L727
https://github.com/videojs/video.js/blob/v6.2.0/src/js/video.js#L726

So the fix to this is as I understand it to switch to ES6 imports or to change the require to `require('video.js).default`

But I'm not really an expert to this subject. 

Explanations of this problem:
https://github.com/videojs/video.js/issues/2698#issuecomment-148151327
https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0

**Comment by thijstriemstra** [comment]
Hmm, @gkatsev should we use `require('video.js).default` as suggested in order to support both versions of video.js?

**Comment by thijstriemstra** [comment]
@alsar I assume you (will) have the same issue with https://github.com/collab-project/videojs-wavesurfer?

**Comment by gkatsev** [comment]
Hm... when making the changes in 6.2.0 I tested to make sure that it works without requiring es6: https://github.com/videojs/videojs-bundler-sample
Maybe the issue is that this is a separate project that requires videojs and not an end-user which is what the bundler-sample project is?

**Comment by gkatsev** [comment]
Though, thinking about it some more, what version of webpack is used? We're outputting both CJS and ESM outputs and specify a `main` and a `module` property in the config. If webpack 2 is used, it probably tries to load the ESM module and things break.

**Comment by thijstriemstra** [comment]
> Maybe the issue is that this is a separate project that requires videojs and not an end-user which is what the bundler-sample project is?

This sounds confusing, can you elaborate?

> If webpack 2 is used, it probably tries to load the ESM module and things break.

@alsar what version are you using?

**Comment by thijstriemstra** [comment]
A new release of this plugin  (in short term) would pin video.js to anything < 6.2.0.

**Comment by gkatsev** [comment]
Actually, I think it's exactly module field issue. Just remembered I had to do: https://github.com/videojs/videojs-bundler-sample/blob/master/src-es5/webpack.config.js#L9-L11
We probably should document that in the webpack guide.


>> Maybe the issue is that this is a separate project that requires videojs and not an end-user which is what the bundler-sample project is?
> This sounds confusing, can you elaborate?

What I meant is that in videojs-bundler-sample, we require video.js directly in that project and we don't have a dependency also require video.js.


It sounds to me like if any module isn't using ESM, things could cause an issue. :(

**Comment by thijstriemstra** [comment]
> It sounds to me like if any module isn't using ESM, things could cause an issue. :(

wtf is ESM. sorry.

**Comment by gkatsev** [comment]
it's ok. ESM is short for ES modules or Ecmascript modules. That is the `import` and `export` syntax. CJS is commonjs, i.e., what nodejs uses and what bundlers used to use.

**Comment by alsar** [comment]
I'm using Webpack 3 now. Had the same problem with version 2.

Webpack with ES6 by default uses `video.es.js`. 
I solved the problem temporarily by aliasing video.js with `node_modules/video.js/dist/video.js` which doesn't use the ES6 syntax. But that is not really a proper fix.

**Comment by thijstriemstra** [comment]
I think I will open a new ticket for video.js, pin video.js to <= 6.1.0, and release a new version of this plugin.

**Comment by thijstriemstra** [comment]
> I'm using Webpack 3 now. Had the same problem with version 2.

video.js will be using webpack 3.1.0 soon it looks like (when this travis build succeeds I suppose): https://github.com/videojs/video.js/pull/4470

**Comment by thijstriemstra** [comment]
I opened https://github.com/videojs/video.js/issues/4580 cc @gkatsev

**Comment by thijstriemstra** [comment]
They committed a fix at https://github.com/videojs/video.js/commit/5e2304837044a09204016a771743b7801261c6ad. You can give that a try @alsar or wait till they release it.

**Comment by alsar** [comment]
I tested it quickly with the newsest video.js release that ships with the fix.
```js
    "video.js": "6.2.8",
    "videojs-record": "1.7.0",
```

but I get an error with webpack `Error: plugin "record" does not exist` (also with other plugins). I currently don't have the time to debug it in the next days, but it's definitely a ES6 issue and also maybe isn't related to the fix. Because I don't get any error with `video.js/dist/video.js`.

**Comment by thijstriemstra** [comment]
@gkatsev any idea?

**Comment by thijstriemstra** [comment]
@perminder-klair can you give it a try with 6.2.8 or newer?

**Comment by gavfu** [comment]
I got the same "Error: plugin 'record' does not exist" with video.js 6.2.8 and videojs-record 1.7.0.

I tried to low versions of video.js and videojs-record, but still get the same error. Do you guys know any workaround to make it workable for now?  Thanks.

**Comment by thijstriemstra** [comment]
@gavfu you tried video.js 6.1.0?

**Comment by gavfu** [comment]
@thijstriemstra yes，I'm trying to use it in an electron app, with webpack 2.2.1。
I even tried video.js 5.19.0 with following configurations in package.json, but still got the error.

    "video.js": "5.19.0",
    "videojs-record": "1.6.0"

**Comment by thijstriemstra** [comment]
@gavfu have you tried an older version of webpack, e.g. 1.x.x? I'm currently refactoring the plugins to ES6 and webpack build so this should get fixed eventually.

**Comment by gavfu** [comment]
@thijstriemstra Not yet, webpack 1.x is deprecated so I'd rather not to downgrade to it. May I know roughly when will the new version plugin be released? Meanwhile, if there are any workable combinations of video.js + videojs-record found, I'm willing to try that...

**Comment by thijstriemstra** [comment]
Without webpack it works fine so your only option is to downgrade for now I think.

**Comment by gavfu** [comment]
I'll try and see, thanks thijstriemstra.  :)

**Comment by alsar** [comment]
@gavfu You can alias `video.js` to use the non-ES6 version. 

Use something like this in your webpack config:
```js 
  resolve: {
    alias: {
      'video.js': path.resolve(__dirname, '../../node_modules/video.js/dist/video.js')
    }
  }
```
This is a quick workaround until this issue is resolved.

**Comment by thijstriemstra** [comment]
Also see #167 for better build system/ES6 etc.

**Comment by thijstriemstra** [comment]
@alsar @gavfu 2.0.0 PR was merged to master branch (containing a fix for this ticket), any help testing before I release 2.0.0 would be appreciated!

**Comment by 12smc120** [comment]
@thijstriemstra 
I'm getting an error
Error: plugin "record" does not exist

Please tell me some solution for this.
